# Generated by Django 2.2.6 on 2019-10-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpdesk', '0001_initial'),
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Employee'),
        ),
    ]
