# Generated by Django 2.2.5 on 2019-10-30 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrapp', '0002_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(default=None, max_length=200)),
                ('machine_serial', models.CharField(default=None, max_length=200)),
                ('machine_quantity', models.IntegerField(default=None)),
                ('assigned', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Employee')),
            ],
        ),
    ]
